mode = "countdown"
duration_secs = 1500
always_on_top = true
opacity = 0.8500000238418579
hot_reload = true

[window]
x = 1506
y = 338
width = 418
height = 249
locked = false

[font]
family = "Segoe UI"
size = 56.0
color = "#FFFFFF"

[tray]
left_click_action = "toggle_window"
show_remaining_tooltip = true
