mode = "stopwatch"
duration_secs = 1010
always_on_top = false
opacity = 0.8500000238418579
hot_reload = true

[window]
x = 727
y = -779
width = 720
height = 495
dpi = 96
locked = false

[font]
family = "Segoe UI"
size = 56.0
color = "#FFFFFF"

[tray]
left_click_action = "toggle_window"
show_remaining_tooltip = true
